### ISSUE TITLE
ads1015

### ISSUE THREAD

**Issue by acopernic** [robert-hh/ads1x15#2]
Hello, 
for the ads1015 i have a problem with your driver. I had to delete the gain on this
ads = ads1x15.ADS1015(i2c, addr)
by adding the gain i have this issue
function takes 4 positional arguments but 5 were given

**Comment by robert-hh** [comment]
Thanks for the note. I'll take a look at it.

**Comment by robert-hh** [comment]
Try to change the beginning of the ADS1015 class to:
```
class ADS1015(ADS1115):
    def __init__(self, i2c, address=0x48, gain=1):
        super().__init__(i2c, address, gain)
```
That adds the missing gain parameter.

**Comment by robert-hh** [comment]
Added the missing parameter to the ADS1015 class in commit a819b84

**Comment by acopernic** [comment]
Thanks. Done and working. The gain is quite useful.

Thank you.
On 24 Jun 2018, at 19:13, robert-hh <notifications@github.com<mailto:notifications@github.com>> wrote:

Try to change the beginning of the ADS1015 class to:

class ADS1015(ADS1115):
    def __init__(self, i2c, address=0x48, gain=1):
        super().__init__(i2c, address, gain)


That adds the missing gain parameter.
