### ISSUE TITLE
Dataformat of ads1115.py

### ISSUE THREAD

**Issue by jomasnash** [robert-hh/ads1x15#9]
Hi Robert,

If you follow the datasheet of the ads1115 your "raw_to_v(self, raw)" should divide by 32768 and not 32767 (line 146).
See chapter 9.5.4 of the TI. datasheet. (notice that the left arrow of figure 33 points to 8001H not 8000H)
I know, in practice you will not notice the difference.

**Comment by robert-hh** [comment]
Thanks. I updated the repository.
